name: Check Fortnite Content

on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  Archive:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run Archive script
        run: |
          bash Archive.sh

          # Add and commit changes
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Updated Content Files"

          # Push changes
          git push origin ${{ github.ref }}